# Generated by Django 3.2.13 on 2023-11-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='rank',
            field=models.IntegerField(choices=[('5', '★★★★★'), ('4', '★★★★'), ('3', '★★★'), ('2', '★★'), ('1', '★'), (None, '선택')]),
        ),
    ]
