# Generated by Django 4.2.7 on 2023-11-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecomment',
            name='score',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
