# Generated by Django 4.2.7 on 2023-11-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_actors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='poster_path',
            new_name='profile_path',
        ),
    ]
